/* eslint-disable prettier/prettier */
/**
 * LOGIN ACTION TYPES
 */
export const LOGIN_LOADER = 'LOGIN_LOADER';
export const DEMO_LOGIN_LOADER = 'DEMO_LOGIN_LOADER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_VERSION_SUCCESS = 'USER_VERSION_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_STATUS_LOADER = 'LOGIN_STATUS_LOADER';
export const LOGIN_STATUS_SUCCESS = 'LOGIN_STATUS_SUCCESS';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

/**
 * TRACKING ACTION TYPES
 */

export const GET_CARS_LOADER = 'GET_CARS_LOADER';
export const GET_CARS_SUCCESS = 'GET_CARS_SUCCESS';
export const GET_CARS_REJECTED = 'GET_CARS_REJECTED';
export const REMOVE_CARS = 'REMOVE_CARS';
export const CHANGE_CAR_NAME_LOADER = 'CHANGE_CAR_NAME_LOADER';
export const CHANGE_CAR_NAME_SUCCESS = 'CHANGE_CAR_NAME_SUCCESS';

/**
 * HISTORY ACTION TYPES
 */
export const GET_ROUTE_HISTORY_LOADER = 'GET_ROUTE_HISTORY_LOADER';
export const GET_ROUTE_HISTORY_SUCCESS = 'GET_ROUTE_HISTORY_SUCCESS';
export const GET_ROUTE_HISTORY_REJECTED = 'GET_ROUTE_HISTORY_REJECTED';
export const REMOVE_ROUTE_HISTORY = 'REMOVE_ROUTE_HISTORY';

/**
 * EVENT ACTION TYPES
 */
export const GET_EVENTS_LOADER = ' GET_EVENTS_LOADER';
export const GET_EVENTS_SUCCESS = '  GET_EVENTS_SUCCESS';
export const GET_EVENTS_REJECTED = '  GET_EVENTS_REJECTED';
export const GET_MORE_EVENTS_LOADER = '  GET_MORE_EVENTS_LOADER';
export const GET_MORE_EVENTS_SUCCESS = '  GET_MORE_EVENTS_SUCCESS';
export const GET_EVENT_DETAILS_LOADER = '  GET_EVENT_DETAILS_LOADER';
export const GET_EVENT_DETAILS_SUCCESS = '  GET_EVENT_DETAILS_SUCCESS';
export const REMOVE_EVENT_DETAILS = '  REMOVE_EVENT_DETAILS';

/**
 * PLACES ACTION TYPES
 */
export const GET_PLACE_MARKERS = 'GET_PLACE_MARKERS';
export const GET_PLACE_ZONE = 'GET_PLACE_ZONE';
export const GET_ROUTES = 'GET_ROUTES';

/**
 * SETTING ACTION TYPES
 */
export const CHANGE_SETTING_VALUE = 'CHANGE_SETTING_VALUE';
export const SAVE_NOTIFICATION_SETTING = 'SAVE_NOTIFICATION_SETTING';
export const UPDATE_NOTIFICATION_SETTING = 'UPDATE_NOTIFICATION_SETTING';

/**
 * OBJECT CONTROL TYPES
 */
export const GET_OBJECT_CONTROL_COMMANDS = 'GET_OBJECT_CONTROL_COMMANDS';
export const SEND_OBJECT_CONTROL_COMMAND_LOADER = 'SEND_OBJECT_CONTROL_COMMAND_LOADER';
export const SEND_OBJECT_CONTROL_COMMAND_SUCCESS = 'SEND_OBJECT_CONTROL_COMMAND_SUCCESS';
export const GET_OBJECT_CONTROL_COMMANDS_LIST_LOADER = 'GET_OBJECT_CONTROL_COMMANDS_LIST_LOADER';
export const GET_OBJECT_CONTROL_COMMANDS_LIST_SUCCESS = 'GET_OBJECT_CONTROL_COMMANDS_LIST_SUCCESS';
export const GET_OBJECT_CONTROL_COMMANDS_LIST_REJECTED = 'GET_OBJECT_CONTROL_COMMANDS_LIST_REJECTED';
